[package]
name = "deno-argon2"
version = "2.0.0"
authors = ["Felix <webmaster@schindlerfelix.de>", "Federico <code@fdionisi.me>"]
edition = "2018"

[lib]
path = "native/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bytes = { version = "1.7.2", features = ["serde"] }
rust-argon2 = "2.1.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.129"
